version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install
  deploy:
    docker:
      - image: circleci/node:7.10
    requires:
      - test
    steps:
      - checkout
      - run: npm run buld    
workflows:
  version: 2
  application_deploy:
    jobs:
      - test
      - deploy:
            requires:
              - test
       
