version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Building......"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Testing......"
      - run: sleep 15 
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    requires:
      - test
    steps:
      - checkout
      - run: echo "Deploying....."    
workflows:
  version: 2
  application_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test
      - deploy
       
