version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: ifconfig 
      - run: npm install
      - run: npm install typescript
      - run: npm run test
      - run: npm run build
  test:
    docker:
      - image: circleci/node:8.11.1
    steps:  
      - checkout
      - run: sleep 30 
      - run: curl -i http://localhost:3000/      
workflows:
  version: 2
  application_deploy:
    jobs:
      - build
      - test
       
