version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Building....."
    branches:
      only:
        - master
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Testing......"
    branches:
      ignore:
        - master
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploying....."
      - run: sleep 5     
workflows:
  version: 2
  application_deploy:
    jobs:
      - build
      - test
      - deploy
