version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: npm install
      - run: npm install typescript
  deploy:
    docker:
      - image: circleci/node:7.10
    requires:
      - test
    steps:
      - checkout
      - run: npm run build    
workflows:
  version: 2
  application_deploy:
    jobs:
      - test
      - deploy:
            requires:
              - test
       
